import { ActivityType, DayPlan, FlightInfo, Accommodation, OutfitAdvice } from './types';

// 穿搭建議邏輯庫 (基於氣溫)
export const OUTFIT_ADVICE_DATABASE: OutfitAdvice[] = [
  {
    minTemp: -10,
    maxTemp: 5,
    title: '🥶 極寒對策',
    description: '發熱衣+毛衣+羽絨外套，圍巾、手套、毛帽請備齊 (洋蔥式穿法)。',
    items: ['發熱衣(極暖)', '羽絨外套', '毛帽', '手套', '圍巾', '暖暖包']
  },
  {
    minTemp: 5,
    maxTemp: 10,
    title: '🧥 冬日保暖',
    description: '發熱衣+長袖上衣+厚大衣/羽絨衣，適合穿靴子。室內外溫差大。',
    items: ['發熱衣', '毛衣/刷毛T', '防風大衣', '厚襪子']
  },
  {
    minTemp: 10,
    maxTemp: 15,
    title: '🌬️ 微涼舒適',
    description: '薄長袖/針織衫 + 風衣/夾克，進出室內方便穿脫。',
    items: ['長袖T恤', '輕羽絨背心', '風衣/夾克', '好走的鞋']
  },
  {
    minTemp: 15,
    maxTemp: 30,
    title: '😌 溫暖舒適',
    description: '薄長袖單穿，備一件薄外套即可。',
    items: ['薄長袖', '薄外套']
  }
];

export const FLIGHTS: { outbound: FlightInfo; inbound: FlightInfo } = {
  outbound: {
    code: 'CI104',
    airline: 'China Airlines',
    depTime: '12:35',
    arrTime: '16:35',
    from: 'TPE (T2)',
    to: 'NRT (成田)',
    terminal: 'T2',
  },
  inbound: {
    code: 'CI101',
    airline: 'China Airlines',
    depTime: '14:35',
    arrTime: '17:40',
    from: 'NRT (成田)',
    to: 'TPE',
    terminal: 'T2',
  },
};

export const HOTELS: Accommodation[] = [
  {
    name: '成田東武飯店 (Narita Tobu Hotel Airport)',
    address: '320-1 Tokko, Narita, Chiba 286-0106, Japan',
    checkIn: '12/12',
    notes: '機場接駁車：第2航廈 1樓25號乘車處。17:10起每20分鐘一班。',
    link: 'https://www.tobuhotel.co.jp/narita/'
  },
  {
    name: '星野富士 (HOSHINOYA Fuji)',
    address: '1408 Oishi, Fujikawaguchiko, Minamitsuru District, Yamanashi 401-0305',
    checkIn: '12/13',
    notes: '頂級露營體驗。Check-in 接待處與客房分開，需搭吉普車上山。',
    link: 'https://hoshinoya.com/fuji/zh-tw/'
  },
  {
    name: '箱根天悠 (Hakone Tenyu)',
    address: '1297 Ninotaira, Hakone, Ashigarashimo District, Kanagawa 250-0407',
    checkIn: '12/15',
    notes: '全客房附設露天溫泉。晚餐 17:30 Buffet。',
    link: 'https://www.tenyu.com/'
  },
  {
    name: '三井花園飯店上野 (Mitsui Garden Hotel Ueno)',
    address: '3-19-7 Higashiueno, Taito City, Tokyo 110-0015',
    checkIn: '12/16',
    notes: '就在上野站對面，交通極方便。',
    link: 'https://www.gardenhotels.co.jp/ueno/'
  }
];

export const ITINERARY: DayPlan[] = [
  {
    date: '12/12',
    dayOfWeek: '(五)',
    title: '啟程．成田抵達',
    weather: {
      temp: '6°C - 13°C',
      condition: '多雲',
      icon: '☁️',
      avgTemp: 9,
    },
    activities: [
      {
        id: 'd1-1',
        time: '12:35',
        title: '華航 CI104 起飛',
        type: ActivityType.Transport,
        locationName: 'Taoyuan International Airport Terminal 2',
        description: '前往 C4 登機口前，先購買「樂沐糕餅舖」麵包當明日早餐。',
        detailedDescription: '快樂的出發日！請務必提早 2.5 小時抵達機場。網友激推的麵包店就在 C4 登機口旁，買了剛好帶上飛機或當明天包車路上的早餐。',
        menuRecommendations: ['松露蔥花麵包', '肉桂捲'],
        photoSpots: ['登機前的護照合照', '飛機雲與機翼'],
        imageUrl: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?q=80&w=800&auto=format&fit=crop',
        tips: ['必買：樂沐糕餅舖'],
        links: [{ label: '網友推薦貼文', url: 'https://www.threads.com/@kenwang721112/post/DLrWF2sSDvd' }]
      },
      {
        id: 'd1-2',
        time: '16:35',
        title: '抵達成田機場 & 接駁',
        type: ActivityType.Transport,
        locationName: 'Narita International Airport Terminal 2',
        description: '入境後前往 1F 25號站牌搭乘飯店接駁車。',
        detailedDescription: '抵達日本！入境後請直接前往 1 樓外面的巴士站。不用買票，直接排隊上車。飯店接駁車在 25 號站牌，時刻表：17:10, 17:30, 17:50, 18:10...',
        photoSpots: ['日本的第一口空氣', '接駁車進站瞬間'],
        imageUrl: 'https://asset.japan.travel/image/upload/v1668563849/chiba/Chiba_t_id264_1.jpg',
        links: [{ label: 'Visit Japan Web (入境登錄)', url: 'https://vjw-lp.digital.go.jp/zh-hant/' }]
      },
      {
        id: 'd1-3',
        time: '18:00',
        title: '晚餐三選一',
        type: ActivityType.Food,
        locationName: 'Aeon Mall Narita',
        description: '1. 機場吃\n2. 飯店加購 Buffet\n3. Aeon Mall (推薦)',
        detailedDescription: 'Aeon Mall 是大型購物中心，飯店有接駁車很方便。如果不累建議去逛逛，超市也很好買。推薦去美食街的海鮮三崎港迴轉壽司。',
        menuRecommendations: ['海鮮三崎港：干貝、鮪魚大腹', '牛角燒肉：橫膈膜'],
        photoSpots: ['迴轉壽司盤疊高高', '超市草莓'],
        imageUrl: 'https://tblg.k-img.com/restaurant/images/Rvw/162140/640x640_rect_162140405.jpg',
        tabelogUrl: 'https://tabelog.com/chiba/A1204/A120401/12000523/',
        tips: ['推薦：海鮮三崎港'],
        links: [{ label: 'Aeon Mall 官網', url: 'https://tw.aeonmall.global/mall/narita' }]
      },
      {
        id: 'd1-4',
        time: 'Check-in',
        title: '成田東武飯店',
        type: ActivityType.Hotel,
        locationName: 'Narita Tobu Hotel Airport',
        description: '簡單過夜，養精蓄銳。',
        detailedDescription: '離機場很近的過境旅館，房間較大，適合整理行李。',
        imageUrl: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?q=80&w=800&auto=format&fit=crop',
      }
    ]
  },
  {
    date: '12/13',
    dayOfWeek: '(六)',
    title: '富士山與天鵝',
    weather: {
      temp: '0°C - 9°C',
      condition: '晴時多雲',
      icon: '🌤️',
      avgTemp: 4,
    },
    activities: [
      {
        id: 'd2-1',
        time: '08:00',
        title: '包車出發',
        type: ActivityType.Transport,
        locationName: 'Narita Tobu Hotel Airport',
        description: '提醒司機：走圈央道，目標山中湖。',
        detailedDescription: '包車可以睡覺補眠，中途會經過休息站。記得提醒司機走圈央道 (Ken-O Expressway) 避開都心車潮。',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToEocJxN-ZdEmEgGc4sUJ8FVAqkMK5NIa7Xw&s',
      },
      {
        id: 'd2-2',
        time: '10:30',
        title: '山中湖 平野之濱',
        type: ActivityType.Sightseeing,
        locationName: 'Hirano no Hama',
        description: '拍巨大富士山與天鵝 (停留約30分)。',
        detailedDescription: '「平野之濱」是山中湖欣賞富士山最著名的地點之一。這裡擁有毫無遮蔽的開闊視野，富士山巨大的山體倒映在平靜湖面上，形成「逆富士」絕景。若運氣好，還能捕捉到優雅的天鵝游過畫面，是無數攝影師夢寐以求的構圖。',
        photoSpots: ['低角度拍天鵝與富士山', '人站在湖邊背影', '逆富士倒影'],
        imageUrl: 'https://sliptojapan.com/wp-content/uploads/2025/04/fujisan-kawaguchiko-spot_%E5%B1%B1%E4%B8%AD%E6%B9%96%E5%B9%B3%E9%87%8E%E3%81%AE%E6%B5%9C-AC.jpeg',
        tips: ['重點行程', '攝影聖地'],
      },
      {
        id: 'd2-3',
        time: '11:20',
        title: '忍野八海 & 午餐',
        type: ActivityType.Sightseeing,
        locationName: 'Oshino Hakkai',
        description: '名水百選。午餐推薦蕎麥麵或草餅。',
        detailedDescription: '忍野八海是富士山世界文化遺產的構成資產之一。這裡的八個池塘水源來自富士山融雪，經過地下熔岩層長達80年的過濾，水質清澈剔透，呈現神祕的藍綠色。這裡的「名水豆腐」和「蕎麥麵」因水質優良而口感極佳，是必嚐美食。',
        menuRecommendations: ['名水蕎麥麵', '烤草餅', '辣味噌豆腐'],
        photoSpots: ['清澈池水中的魚', '水車與富士山', '鏡池'],
        imageUrl: 'https://s3-ap-northeast-1.amazonaws.com/thegate/2021/02/12/17/05/19/Oshino-Hakkai.jpg',
        tabelogUrl: 'https://tabelog.com/tw/yamanashi/A1903/A190302/19001633/',
        tips: ['必吃：名水蕎麥麵'],
      },
      {
        id: 'd2-4',
        time: '13:10',
        title: '河口湖美食巡禮',
        type: ActivityType.Food,
        locationName: 'Fujisan Shokupan',
        description: '必買：Fujisan Shokupan 藍白吐司 & 藍色果凍。',
        detailedDescription: '河口湖車站周邊的網美補給站！Fujisan Shokupan 使用山梨縣產小麥與富士山天然水，製作出切面呈現藍白富士山圖案的吐司，不僅造型吸睛，口感也柔軟香甜。Tsunagaru Cafe 則有夢幻的藍色富士山果凍。',
        menuRecommendations: ['富士山吐司', '富士山藍色果凍'],
        photoSpots: ['手拿富士山吐司對比真富士山', '藍色果凍透光照'],
        imageUrl: 'https://d20aeo683mqd6t.cloudfront.net/zh-hant/articles/title_images/000/040/010/medium/meitu_10.jpg?2020',
        tabelogUrl: 'https://tabelog.com/tw/yamanashi/A1903/A190303/19011342/',
        tips: ['網美打卡必備'],
      },
      {
        id: 'd2-5',
        time: '14:20',
        title: '【任務】馬拉松領物資',
        type: ActivityType.Mission,
        locationName: 'Oike Park Kawaguchiko',
        description: '地點：河口湖大池公園。逛 EXPO，確認明天動線。',
        detailedDescription: '感受賽前熱鬧氣氛，記得試穿紀念T恤尺寸。現場有很多攤位可以逛，可以買到限量的馬拉松周邊商品。記得再次確認明天的寄物動線。',
        photoSpots: ['號碼布合照', 'EXPO 拱門'],
        imageUrl: 'https://www.japankuru.com/gld-kanri/data/uploads/2024/05/IMG_5104_VSCO-800x450.jpg',
      },
      {
        id: 'd2-6',
        time: '15:20',
        title: 'Ogino 超市採買',
        type: ActivityType.Shopping,
        locationName: 'Ogino Kawaguchiko',
        description: '晚餐(熟食/壽司/飯糰)、明天早餐、香蕉、水、麝香葡萄。',
        detailedDescription: '超市爆買行程！重點是買好明天的早餐與補給（香蕉、優格、能量凍）。晚餐也可以直接買超市的高級熟食和壽司回飯店吃。',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSI4VKbbBa_SclQmZu2e1bcmn2KdrJJwS4g9w&s',
        tips: ['賽前補給'],
      },
      {
        id: 'd2-7',
        time: '16:00',
        title: '星野富士 Check-in',
        type: ActivityType.Hotel,
        locationName: 'HOSHINOYA Fuji',
        description: '迎賓下午茶，整理號碼布，早點休息。',
        detailedDescription: '房間陽台就能看富士山。下午有戶外營火與棉花糖體驗。晚餐建議在房間享用超市買的美食，或是預訂好的餐點。',
        menuRecommendations: ['露營風晚餐'],
        photoSpots: ['陽台暖爐桌', '森林中的營火'],
        imageUrl: 'https://media.hoshinoresorts.com/image/authenticated/s--CnZc_o6b--/c_crop,h_3360,w_6720,x_0,y_507/c_scale,h_3360,w_6720/c_fill,g_auto,h_600/f_auto,q_auto/v1679368005/Cabin_Autumn_Exterior_-_HOSHINOYA_Fuji_t4lpel.jpg',
      }
    ]
  },
  {
    date: '12/14',
    dayOfWeek: '(日)',
    title: '決戰富士山馬拉松',
    weather: {
      temp: '-2°C - 8°C',
      condition: '晴朗',
      icon: '☀️',
      avgTemp: 3,
    },
    activities: [
      {
        id: 'd3-1',
        time: '06:00',
        title: '早餐',
        type: ActivityType.Food,
        locationName: 'HOSHINOYA Fuji',
        description: '富士山吐司 + 超商咖啡。',
        detailedDescription: '賽前飲食以好消化碳水為主。別忘了保暖。',
        imageUrl: 'https://tiyama.net/wp-content/uploads/2023/09/Fujisan-Shokupan.jpg',
      },
      {
        id: 'd3-2',
        time: '09:00',
        title: '全馬組起跑 🔫',
        type: ActivityType.Marathon,
        locationName: 'Kawaguchiko Marathon Start Line',
        description: 'Enjoy the Run! 世界上最美的賽道。',
        detailedDescription: '全馬組起跑！看著富士山跑步是種享受。前段環繞河口湖平坦舒適，中段西湖有些許坡度挑戰，但風景絕對值回票價。',
        photoSpots: ['起跑線', '完賽獎牌與富士山'],
        imageUrl: 'https://japankuru.com/gld-kanri/data/uploads/2024/05/GL-sQyJaUAA09x0-800x533.jpg',
        tips: ['加油！'],
      },
      {
        id: 'd3-3',
        time: '11:30',
        title: '慈善組午餐',
        type: ActivityType.Food,
        locationName: 'Royal Host Kawaguchiko',
        description: 'Royal Host 或 Gusto (大池公園旁)。',
        detailedDescription: '慈善組跑完後，可以在這裡吃午餐吹暖氣，等待全馬跑者歸來。日本的家庭餐廳選擇多，漢堡排和聖代都很棒。',
        menuRecommendations: ['漢堡排', '草莓聖代'],
        tabelogUrl: 'https://tabelog.com/yamanashi/A1903/A190303/19000722/',
        imageUrl: 'https://images.unsplash.com/photo-1554502078-ef0fc409efce?q=80&w=800&auto=format&fit=crop',
      },
      {
        id: 'd3-4',
        time: '15:00',
        title: '天上山公園纜車',
        type: ActivityType.Sightseeing,
        locationName: 'Mt. Fuji Panoramic Ropeway',
        description: '賽後輕鬆看風景。',
        detailedDescription: '搭乘纜車僅需3分鐘即可抵達山頂。這裡是以日本童話故事「喀嚓喀嚓山」為背景，到處都有可愛的兔子和狸貓裝飾。展望台可以無死角俯瞰河口湖全景與富士山。',
        menuRecommendations: ['狸貓糰子'],
        photoSpots: ['兔子神社', '天上的鐘', '展望台全景'],
        imageUrl: 'https://sliptojapan.com/wp-content/uploads/2024/12/mt-fuji-ropeway_1-%E5%AE%98%E7%B6%B2.jpeg',
      },
      {
        id: 'd3-5',
        time: '18:00',
        title: '星野晚餐',
        type: ActivityType.Food,
        locationName: 'HOSHINOYA Fuji',
        description: '慶功宴 (需預約)。',
        detailedDescription: '跑完步後的豪華晚餐，好好犒賞自己。',
        imageUrl: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?q=80&w=800&auto=format&fit=crop',
      }
    ]
  },
  {
    date: '12/15',
    dayOfWeek: '(一)',
    title: '箱根溫泉療癒',
    weather: {
      temp: '3°C - 10°C',
      condition: '多雲時晴',
      icon: '⛅',
      avgTemp: 6,
    },
    activities: [
      {
        id: 'd4-1',
        time: '07:30',
        title: '星野早餐 Box',
        type: ActivityType.Food,
        locationName: 'HOSHINOYA Fuji',
        description: '在房間陽台享用 Morning Box。',
        detailedDescription: '星野招牌的 Morning Box，背著木箱在陽台面對富士山野餐，是絕佳的體驗。',
        menuRecommendations: ['荷蘭鍋麵包', '湯品'],
        photoSpots: ['木箱早餐與富士山', '陽台手沖咖啡'],
        imageUrl: 'https://bitesize.tw/wp-content/uploads/20170804130325_43.jpg',
        tips: ['必拍體驗'],
      },
      {
        id: 'd4-2',
        time: '08:30',
        title: '新倉山淺間公園',
        type: ActivityType.Sightseeing,
        locationName: 'Arakurayama Sengen Park',
        description: '五重塔與富士山 (1.5小時)。',
        detailedDescription: '這是一張代表日本的明信片！紅色的五重塔（忠靈塔）配上背景的富士山，是外國遊客必訪景點。雖然需要攀爬398階樓梯，但山頂的景色絕對值得。跑者若腿部不適，可在山下的新倉富士淺間神社參拜即可。',
        photoSpots: ['五重塔+櫻花/紅葉+富士山'],
        imageUrl: 'https://fujiyoshida.net/image/rendering/attraction_image/13/trim.900/3/2?v=9893e783c7d93fc6177ea5d24072b4fa767b9b40',
      },
      {
        id: 'd4-3',
        time: '11:00',
        title: '午餐：田村銀勝亭',
        type: ActivityType.Food,
        locationName: 'Tamura Ginkatsutei',
        description: '必吃：豆腐豬排煮 (利用早到優勢第一批吃)。',
        detailedDescription: '箱根強羅的名店，創業於昭和48年。招牌菜「豆腐豬排煮」是將豆腐夾入絞肉油炸，再放入陶鍋中以甘甜的高湯燉煮，口感滑嫩，非常適合賽後補充蛋白質。',
        menuRecommendations: ['豆腐豬排煮定食'],
        photoSpots: ['剛上桌冒煙的陶鍋'],
        tabelogUrl: 'https://tabelog.com/tw/kanagawa/A1410/A141001/14001492/',
        imageUrl: 'https://kimiyo.tw/wp-content/uploads/20210711164417_61.jpg',
        tips: ['必吃美食'],
      },
      {
        id: 'd4-4',
        time: '13:00',
        title: '大涌谷',
        type: ActivityType.Sightseeing,
        locationName: 'Owakudani',
        description: '吃黑蛋延年益壽。',
        detailedDescription: '約3000年前箱根火山爆發形成的火山口遺跡，至今仍不斷噴出硫磺蒸氣，舊稱「地獄谷」。必吃利用地熱煮熟的「黑蛋」，據說吃一顆可以延壽7年。',
        menuRecommendations: ['黑蛋 (延壽7年)'],
        photoSpots: ['手拿黑蛋與冒煙的地熱', '大涌谷地標'],
        imageUrl: 'https://tw.wamazing.com/media/wp-content/uploads/sites/4/2024/05/kanagawaItinerary01_pixta_88673008_M-853x569.jpg.webp',
      },
      {
        id: 'd4-5',
        time: '14:30',
        title: '蘆之湖 & 箱根神社',
        type: ActivityType.Sightseeing,
        locationName: 'Hakone Shrine',
        description: 'Bakery & Table 喝咖啡，水上鳥居打卡。',
        detailedDescription: '箱根神社已有1200年歷史，是關東總鎮守。矗立在蘆之湖水面上的紅色「平和鳥居」是非常夢幻的打卡點。附近的 Bakery & Table Hakone 可以一邊泡足湯一邊吃麵包看湖景。',
        photoSpots: ['站在鳥居下拍剪影', '湖畔倒影'],
        imageUrl: 'https://www.hokkaidolibrary.com/img/upload/Japan/KANTO/302-01.jpg',
      },
      {
        id: 'd4-6',
        time: '16:30',
        title: '箱根天悠 Check-in',
        type: ActivityType.Hotel,
        locationName: 'Hakone Tenyu',
        description: '享受露天溫泉，舒緩肌肉。',
        detailedDescription: '全館都有露天溫泉的奢華旅館。17:30 享用飯店 Buffet。',
        imageUrl: 'https://pix10.agoda.net/hotelImages/1410571/-1/492cf02443e7e0941520540c6ff95692.jpg?ce=0&s=414x232',
      }
    ]
  },
  {
    date: '12/16',
    dayOfWeek: '(二)',
    title: '重返東京聖誕',
    weather: {
      temp: '7°C - 14°C',
      condition: '晴天',
      icon: '☀️',
      avgTemp: 10,
    },
    activities: [
      {
        id: 'd5-1',
        time: '11:30',
        title: '午餐：淺草今半',
        type: ActivityType.Food,
        locationName: 'Asakusa Imahan',
        description: '百年壽喜燒 (或伊豆榮鰻魚飯)。',
        detailedDescription: '創業於明治28年的壽喜燒老店。使用日本頂級黑毛和牛，搭配秘傳醬汁，肉質入口即化。午間套餐價格相對親民，是體驗頂級和牛的好機會。',
        menuRecommendations: ['百年牛丼', '壽喜燒御膳'],
        photoSpots: ['和牛油花', '淋上蛋液的肉'],
        tabelogUrl: 'https://tabelog.com/tw/tokyo/A1311/A131102/13003649/',
        imageUrl: 'https://tblg.k-img.com/restaurant/images/Rvw/85451/640x640_rect_85451882.jpg',
        tips: ['必吃美食'],
      },
      {
        id: 'd5-2',
        time: '13:30',
        title: '晴空塔 & 淺草雷門',
        type: ActivityType.Sightseeing,
        locationName: 'Tokyo Skytree',
        description: '逛街購物。',
        detailedDescription: '淺草寺雷門的大紅燈籠是東京最著名的象徵。參拜後前往世界最高的自立式電波塔「晴空塔」，底下是巨大的購物中心 Solamachi，非常好買伴手禮。',
        menuRecommendations: ['人形燒', '炸肉餅'],
        photoSpots: ['雷門大燈籠', '晴空塔全景'],
        imageUrl: 'https://www.bring-you.info/imgs/2019/05/senso-ji-1-900x611.jpg',
      },
      {
        id: 'd5-3',
        time: '17:30',
        title: '三井花園飯店上野 Check-in',
        type: ActivityType.Hotel,
        locationName: 'Mitsui Garden Hotel Ueno',
        description: '放置行李。',
        detailedDescription: '就在上野站對面，交通極方便。',
        imageUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&q=80&w=1000',
      },
      {
        id: 'd5-4',
        time: '18:30',
        title: '東京聖誕 Advent',
        type: ActivityType.Sightseeing,
        locationName: 'Ueno Park',
        description: '上野恩賜公園 袴腰廣場 (飯店對面)。',
        detailedDescription: '就在飯店對面，感受熊貓聖誕樹與熱紅酒的歐洲風情市集。',
        menuRecommendations: ['熱紅酒', '德國香腸'],
        photoSpots: ['聖誕樹燈飾', '手拿熱紅酒'],
        imageUrl: 'https://static.wixstatic.com/media/3eef8e_7899e6a1000249ce9446fa71cfe2cf74~mv2.jpg/v1/fill/w_568,h_320,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/3eef8e_7899e6a1000249ce9446fa71cfe2cf74~mv2.jpg',
        tips: ['期間限定'],
      },
      {
        id: 'd5-5',
        time: '晚餐',
        title: '上野周邊美食',
        type: ActivityType.Food,
        locationName: 'Ueno',
        description: '聖誕市集 / 一蘭 / 鴨to蔥 / 燒肉。',
        detailedDescription: '推薦「鴨to蔥」拉麵，湯頭鮮甜，但可能要排隊。',
        menuRecommendations: ['鴨to蔥拉麵'],
        tabelogUrl: 'https://tabelog.com/tw/tokyo/A1311/A131101/13210392/',
        imageUrl: 'https://tblg.k-img.com/resize/660x370c/restaurant/images/Rvw/188155/3c2b5c06ca1bfd1751ef66997f8e163e.jpg?token=8026d01&api=v2',
      }
    ]
  },
  {
    date: '12/17',
    dayOfWeek: '(三)',
    title: '滿載而歸',
    weather: {
      temp: '8°C - 15°C',
      condition: '晴',
      icon: '☀️',
      avgTemp: 11,
    },
    activities: [
      {
        id: 'd6-1',
        time: '08:00',
        title: '上野公園',
        type: ActivityType.Sightseeing,
        locationName: 'Ueno Park',
        description: '看看還有沒有銀杏。',
        detailedDescription: '早晨的公園空氣很好，可能有殘留的銀杏。',
        imageUrl: 'https://ginatw.com/wp-content/uploads/2021/11/IMG_2820.jpg',
      },
      {
        id: 'd6-2',
        time: '09:00',
        title: '阿美橫丁 / 多慶屋',
        type: ActivityType.Shopping,
        locationName: 'Ameyoko',
        description: '最後補貨 (藥妝/零食)。',
        detailedDescription: '二木的菓子買零食，藥妝店最後衝刺。',
        menuRecommendations: ['二木的菓子'],
        imageUrl: 'https://images.unsplash.com/photo-1582235940562-432243d489af?q=80&w=800&auto=format&fit=crop',
      },
      {
        id: 'd6-3',
        time: '11:00',
        title: '搭乘 Skyliner',
        type: ActivityType.Transport,
        locationName: 'Keisei Ueno Station',
        description: '前往成田機場。',
        detailedDescription: '最快到機場的交通方式，記得先買好票。',
        imageUrl: 'https://images.unsplash.com/photo-1517154421773-052f79edd517?q=80&w=800&auto=format&fit=crop',
      },
      {
        id: 'd6-4',
        time: '14:35',
        title: '班機 CI101 返台',
        type: ActivityType.Transport,
        locationName: 'Narita International Airport',
        description: '平安回家。',
        detailedDescription: '抵達溫暖的家。',
        imageUrl: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?q=80&w=800&auto=format&fit=crop',
      }
    ]
  }
];